#include<stdio.h>
#include<omp.h>
#include<time.h>
clock_t st, en;
float p;
int fib(int n);
int n;
int main()
{
    int r[100], i;
    printf("enter n:");
    scanf("%d", &n);
    omp_set_num_threads(2);
#pragma omp parallel
    {
#pragma omp critical
        {
            if (omp_get_thread_num() == 0) {
                printf("fibonaccy series is generated by thread%d\n", omp_get_thread_num());
                st = clock();
                for (i = 0; i < n; i++) {
                    r[i] = fib(i);
                }
                en = clock();
            } else {
                printf("fibonaccy series is displayed by thread%d\t", omp_get_thread_num());
                for (i = 0; i < n; i++) {
                    printf("%d\n", r[i]);
                }
            }
        }
    }
    p = (en - st);
    printf("time required is:%f\n", p / CLOCKS_PER_SEC);
    return 0;
}

int fib(int n)
{
    if (n == 0)
        return 0;
    else if (n == 1)
        return 1;
    else
        return fib(n - 1) + fib(n - 2);
}
